[package]
name = "assembler"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
isa = { path = "../isa" }
regex = "1.10.4"
once_cell = "1.19.0"
num = "0.4.2"
serde_json = "1.0"

