name: Rust

on:
  push

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install libraries
        run: |
          python -m pip install --upgrade pip
          pip install pytest-golden

      # Testing file builds project
      # I would rather put build as separate step or a job
      # But building wihtin tests is just easier by alot
      - name: Run tests
        run: |
          pytest


  lint:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Run basic checks
      run: cargo check
    - name: Run linter
      run: cargo clippy
